#!/usr/bin/env python3
"""Build FBI/IC3 law-enforcement packages (defensive TI handoff only)."""
from __future__ import annotations

import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
LE = ROOT / "reports" / "law-enforcement"
PACKAGES = LE / "packages"

FAMILIES = [
    {
        "id": "01-rapuncel",
        "family": "Rapuncel",
        "slug": "rapuncel",
        "case_code": "ETW-RAP-IC3",
        "platform": "Windows",
        "threat_type": "Information stealer / MaaS distribution (credential theft)",
        "ic3_crime_types": "Malware; Phishing / social engineering (SEO/GitHub lure); Identity theft facilitation",
        "fbi_relevance": (
            "Interstate cyber intrusion facilitation; credential theft targeting "
            "financial/password vault ecosystem; fraudulent brand impersonation on GitHub"
        ),
        "primary_orgs": (
            "LastPass TIME + Delphos (primary); eSentire / Proofpoint "
            "(Cruciferra crypter context); Trend Micro (BoryptGrab comparator only)"
        ),
        "primary_urls": [
            "https://blog.lastpass.com/posts/lastpass-delphos-report-rapuncel-infostealer",
            "https://www.esentire.com/blog/malware-as-a-service-cocktail-errtraffic-and-cruciferra-killing-your-edr-since-2025",
            "https://www.proofpoint.com/us/blog/threat-insight/unpacking-cruciferra-analysis-sophisticated-crypter-service",
            "https://www.trendmicro.com/en_us/research/26/c/boryptgrab-stealer-targets-users-via-deceptive-github-pages.html",
            "https://raw.githubusercontent.com/eSentire/iocs/main/Cruciferra/cruciferra-IoCs-08-12-2026.txt",
            "https://raw.githubusercontent.com/eSentire/iocs/main/Cruciferra/cruciferra_sideloaded_apps.csv",
            "https://www.loldrivers.io/drivers/3e3067b0-3d74-46fe-9f57-1ae3a0293958/",
        ],
        "pub_date": "2026-09-17 (LastPass/Delphos primary)",
        "observed_infra": (
            "OBSERVED_PASSIVE only (not campaign ownership): additional GitHub Pages lure "
            "massimolongqdoj.github.io→albinofennel.com; passathook-cs2 path on albinofennel; "
            "CT chronology; DoH NXDOMAIN for albinofennel.com as of 2026-09-19. Cruciferra "
            "DCRCVDrv/vsdbg sideload catalog and LOLDrivers CcProtect are lineage comparators — "
            "not Rapuncel-author identity."
        ),
        "indicators_path": ROOT
        / "investigations"
        / "rapuncel"
        / "evidence"
        / "published-indicators.csv",
        "narrative": (
            "I am reporting defensive threat-intelligence information concerning a malware "
            "distribution operation publicly documented as Rapuncel. LastPass TIME and Delphos "
            "published research on September 17, 2026 describing fraudulent, SEO-oriented GitHub "
            "repositories and GitHub Pages used to distribute a Windows information stealer. The "
            "reported chain used legitimate Microsoft vsdbg.exe for DLL sideloading and a malicious "
            "vsdbg.dll loader that the researchers assessed with high confidence as generated by "
            "Cruciferra/PUROSANGUE or a close derivative. Cruciferra is a crypter/delivery tooling "
            "context only; I am not equating Cruciferra authors or operators with the Rapuncel "
            "stealer author. The researchers published malware hashes, infrastructure domains and "
            "IP addresses. Passive follow-up (urlscan/CT/DoH) separately recorded an additional "
            "GitHub Pages lure host massimolongqdoj.github.io redirecting to albinofennel.com, "
            "certificate-transparency chronology for campaign domains, and NXDOMAIN for "
            "albinofennel.com as of September 19, 2026. eSentire Cruciferra IOC material "
            "(DCRCVDrv.sys / vsdbg sideload catalog) and the LOLDrivers CcProtect reference are "
            "retained as lineage comparison only. I have retained the original public research "
            "and indicator records. Independently validated infrastructure is labeled "
            "OBSERVED_PASSIVE and is not actor-ownership proof."
        ),
        "key_caveats": [
            "Cruciferra ≠ Rapuncel author/operator — shared crypter/BYOVD tooling class only (DCRCVDrv ≠ Alinubx).",
            "Do not credit Cruciferra crypter capabilities to the Rapuncel stealer author without separate evidence.",
            "Cloudflare-fronted IPs have low specificity; prefer domains over CDN edge addresses.",
            "BoryptGrab is a lineage comparator only — same operator is not established.",
            "albinofennel.com NXDOMAIN (DoH 2026-09-19) is a DNS fact — not proof infrastructure is permanently gone.",
            "OBSERVED_PASSIVE lure/CT/DNS facts are not campaign-ownership claims.",
        ],
        "key_indicators_highlight": [
            "SHA-256 samples (vsdbg.dll, Rapuncel, Alinubx.sys) — see 03_INDICATORS.csv (RAP-IND-0001–0036)",
            "Domains: albinofennel.com (NXDOMAIN as of 2026-09-19 DoH), hanselarinmusky.com, icansamyope.com, istatlmenus.com, macperformancetools.com, zaffersnouty.com",
            "Exfil IP (primary-reported): 2.26.126.50",
            "Fraudulent GitHub: github.com/LastPass-Authenticator; lastpass-authenticator.github.io; massimolongqdoj.github.io (OBSERVED_PASSIVE lure)",
            "Lineage-only (not Rapuncel campaign unless linked): Cruciferra DCRCVDrv SHA-256; device \\\\.\\DCRCVDRV_U; LOLDrivers CcProtect baseline",
        ],
        "impact": (
            "Credential and browser/wallet theft enabling downstream fraud and account takeover. "
            "Brand impersonation of password-manager ecosystem increases trust abuse."
        ),
        "not_claiming": [
            "No personal victimization claim in this package unless separately documented by the reporter.",
            "No dollar loss figure.",
            "No assertion that ETW discovered Rapuncel.",
            "No claim that Cruciferra equals Rapuncel operators or authors.",
            "No claim that DCRCVDrv or Cruciferra mscoree.dll are Rapuncel delivery artifacts without independent linkage.",
        ],
    },
    {
        "id": "02-settra",
        "family": "Settra",
        "slug": "settra",
        "case_code": "ETW-SET-IC3",
        "platform": "Windows (enterprise)",
        "threat_type": "Ransomware / extortion (encryptor + human-operated intrusion)",
        "ic3_crime_types": "Ransomware; Extortion; Unauthorized network intrusion (operator activity)",
        "fbi_relevance": (
            "Enterprise ransomware with documented MeshAgent C2 IPs and BYOVD/"
            "defense-impairment tooling in IR reporting"
        ),
        "primary_orgs": (
            "Cynet Research Labs; Huntress; MOXFIVE; Kaspersky GERT "
            "(WIN-LIVFRVQFMKO SSL-CN historical lead only — not Settra attribution)"
        ),
        "primary_urls": [
            "https://www.cynet.com/settra-ransomware-inside-a-new-enterprise-grade-extortion-threat/",
            "https://www.cynet.com/blog/inside-cynets-settra-ransomware-investigation/",
            "https://www.huntress.com/blog/new-settra-ransomware-variant",
            "https://www.moxfive.com/blog/settra-ransomware-ttps-victims-and-defense-guide",
            "https://securelist.com/patched-forticlient-ems-vulnerability-exploited-in-the-wild/115046/",
        ],
        "pub_date": "2026-07 to 2026-09 (multi-vendor IR / RE)",
        "observed_infra": (
            "OBSERVED_PASSIVE only (not campaign ownership): RDAP NL-RAPIDSEEDBOX for "
            "193.5.65.114; urlscan MeshCentral Login / id-manulife.com same-IP chronology from "
            "2025-05 — INFRASTRUCTURE_OVERLAP / UNKNOWN, not Settra-exclusive."
        ),
        "indicators_path": ROOT
        / "investigations"
        / "settra"
        / "evidence"
        / "published-indicators.csv",
        "narrative": (
            "I am reporting defensive threat-intelligence information concerning ransomware/"
            "extortion activity publicly tracked as Settra. Cynet, Huntress and MOXFIVE have "
            "independently published incident-response or technical findings related to this "
            "operation. Cynet reverse engineered a password-gated two-stage Windows encryptor and "
            "found that the encryptor itself did not contain file-exfiltration functionality. "
            "Huntress reported two incidents using MeshAgent and identified 45.13.122.7 and "
            "193.5.65.114 as MeshAgent infrastructure during those incidents. Huntress also "
            "reported the workstation identifier WIN-LIVFRVQFMKO, which it had observed in other "
            "malicious activity before Settra's public emergence. Kaspersky GERT separately "
            "documented WIN-LIVFRVQFMKO as an SSL certificate common name on port 7777 of a "
            "Hetzner-hosted host during FortiClient EMS exploitation research — that sighting is "
            "a multi-campaign hostname lead and is not Settra-exclusive. Passive urlscan "
            "observations show MeshCentral panels on 193.5.65.114 earlier than the Huntress "
            "association window (including id-manulife.com overlap), and RDAP lists the address "
            "under Rapid Seedbox allocation NL-RAPIDSEEDBOX-20250306. I am retaining these "
            "historical relationships as investigative leads and am not attributing the older "
            "incidents or hosting allocation to Settra without additional evidence."
        ),
        "key_caveats": [
            'Encryptor (malware) and operator intrusion tooling are separate — do not say "Settra uses Mimikatz."',
            "WIN-LIVFRVQFMKO is an investigative lead (Huntress + Kaspersky SSL CN) — UNKNOWN / not Settra-exclusive; do not backdate Settra to 2024.",
            "193.5.65.114 MeshCentral chronology and Rapid Seedbox RDAP are INFRASTRUCTURE_OVERLAP leads — not Settra-exclusive ownership.",
            "Public pages analyzed for this corpus did not yield a usable Settra sample SHA-256 list.",
            "OBSERVED_PASSIVE MeshCentral/RDAP facts are not campaign-ownership claims.",
        ],
        "key_indicators_highlight": [
            "MeshAgent C2 IPv4: 45.13.122.7 (July 2026 Huntress); 193.5.65.114 (Sept 2026 Huntress; earlier MeshCentral OBSERVED_PASSIVE — not exclusive)",
            "Workstation lead: WIN-LIVFRVQFMKO (Huntress + Kaspersky SSL CN — not Settra-exclusive proof)",
            "Overlap leads: id-manulife.com; tlsIssuer MeshCentralRoot-eca57f (SET-IND-0015/0016)",
            "Ransom notes: RESTORE_FILES.txt / RESTORE_FILES.html",
            "Extensions: .locked / .locked_wip; naming pattern *_win64.exe",
            "BYOVD filenames: gdrv.sys; STProcessMonitor_v114.sys (operator tooling context)",
        ],
        "impact": (
            "Enterprise encryption/extortion; recovery destruction; possible data theft by "
            "operators using tooling separate from the encryptor binary."
        ),
        "not_claiming": [
            "No victim organization names invented.",
            "No dollar loss figure.",
            "No claim that pre-2026 hostname sightings prove Settra existed then.",
            "No claim that Kaspersky FortiClient EMS activity is Settra.",
            "No claim that encryptor itself performs exfiltration.",
            "No claim that Rapid Seedbox RDAP contacts identify malware authors.",
        ],
    },
    {
        "id": "03-rathat",
        "family": "RatHat",
        "slug": "rathat",
        "case_code": "ETW-RAT-IC3",
        "platform": "Android",
        "threat_type": "Android banking RAT / credential theft (Accessibility + Wireless ADB abuse)",
        "ic3_crime_types": "Malware (mobile); Online banking fraud facilitation; Unauthorized access to devices",
        "fbi_relevance": (
            "Mobile malware obtaining Android shell via Wireless Debugging self-pair; "
            "persistence outside APK lifecycle; credential and banking targeting"
        ),
        "primary_orgs": "Zimperium zLabs",
        "primary_urls": [
            "https://zimperium.com/blog/rathat-ai-powered-mobile-threat-is-here-for-your-credentials-bank-accounts",
            "https://github.com/Zimperium/IOC/tree/master/2026-09-RatHat",
        ],
        "pub_date": "2026-09-16 (Zimperium)",
        "observed_infra": (
            "None as live C2 contact. Passive CT/urlscan rows exist for selected Zimperium-published "
            "apexes (facts only; not ownership)."
        ),
        "indicators_path": ROOT
        / "investigations"
        / "rathat"
        / "evidence"
        / "published-indicators.csv",
        "narrative": (
            "I am reporting defensive threat-intelligence information concerning Android malware "
            "publicly named RatHat by Zimperium zLabs on September 16, 2026. Zimperium reports that "
            "the malware abuses Android Accessibility (Accessibility engine class SystemHelperService) "
            "to enable Wireless Debugging, retrieve the device's local ADB pairing information, "
            "self-pair with the local ADB daemon and obtain shell-level execution. It then stages "
            "native Go components outside the ordinary APK lifecycle, including a local service and "
            "an FRP-derived reverse-tunnel component (fatedier/frp; runtime FrpsAddr/FrpsPort/FrpsToken "
            "via main.fetchFrpcConfigFromServer). Zimperium reports keypad-geometry artifact "
            "locateValues.json and that the surviving service can reinstall the APK after removal and "
            "restore Accessibility configuration. Zimperium published companion IOC files under "
            "github.com/Zimperium/IOC/tree/master/2026-09-RatHat (apks.csv, c2.csv, phishing.csv). "
            "I have not actively connected to suspected RatHat command-and-control infrastructure. "
            "Android applicationId / package names remain unpublished in reachable primary sources "
            "and are not invented here."
        ),
        "key_caveats": [
            "Blog body is architectural/URI-path heavy; C2 hosts and APK hashes come from Zimperium's "
            "published IOC tree — do not invent additional hosts, hashes, or package names.",
            "Android applicationId / signing certificates are still open gaps — do not fabricate package names.",
            'Prefer architectural/URI-path indicators and remediation facts over "AI malware" marketing framing.',
            "Uninstalling the visible APK may not remove compromise.",
            "Passive CT/urlscan on published apexes is not ownership or live C2 proof; ETW has not contacted C2.",
        ],
        "key_indicators_highlight": [
            "Native / service: liblocal-service.so; libmedia_codec.so (FRP-derived); SystemHelperService; locateValues.json",
            "Local service: 127.0.0.1:7910; staging /data/local/tmp",
            "URI paths: /api/adbk/upload; /api/tun/config; /api/data/credentials; /api/node/register",
            "Zimperium c2.csv examples: fegrs.adidasabc.com; admin.xiongmaocs.help; oop.uuokxx.com; andxxxo.com",
            "Zimperium phishing.csv examples: kingbss.com; app.tmgg01.top; primevoria.com; S3 APK URL (do not download)",
            "Representative APK SHA-256 from apks.csv (162 total listed by vendor): see RAT-IND-0040",
            "Anti-analysis: Frida probe 27042/tcp; getevent on /dev/input",
            "Package names: not published — do not invent",
        ],
        "impact": (
            "Credential and banking-account compromise; remote shell/tunnel access; "
            "persistence that can survive naive APK removal."
        ),
        "not_claiming": [
            "No invented Android package names or signing certificates.",
            "No dollar loss figure.",
            "No active probing of RatHat C2 by ETW.",
            "No authorship attribution beyond Zimperium's published assessment.",
            "No claim that passive CT/urlscan proves current C2 activity or ownership.",
        ],
    },
    {
        "id": "04-noderabbit",
        "family": "NodeRabbit",
        "slug": "noderabbit",
        "case_code": "ETW-NRB-IC3",
        "platform": "Windows / Linux / macOS / WSL",
        "threat_type": "Cross-platform RAT (developer workstation targeting via fake coding assessments)",
        "ic3_crime_types": (
            "Malware; Spear-phishing / social engineering (recruitment lure); "
            "Espionage-oriented unauthorized access"
        ),
        "fbi_relevance": (
            "Cross-platform spyware targeting MEA developer environments; Azure/Cloudflare-backed "
            "C2; mutable C2 lists; fake VS Code extension and Git-hook persistence"
        ),
        "primary_orgs": "Kaspersky GReAT / Securelist (primary); Kaspersky press (campaign summary)",
        "primary_urls": [
            "https://securelist.com/mirage-kitten-new-backdoors-noderabbit-pollcat/121244/",
            "https://www.kaspersky.com/about/press-releases/kaspersky-great-uncovers-linkedin-recruitment-phishing-and-new-cross-platform-spyware-targeting-mea-by-mirage-kitten",
            "https://blog.polyswarm.io/the-job-offer-has-claws-mirage-kitten-deploys-noderabbit-and-pollcat",
        ],
        "pub_date": "2026-09-01 (Securelist); 2026-09 (press); PolySwarm companion",
        "indicators_path": ROOT
        / "investigations"
        / "noderabbit"
        / "evidence"
        / "published-indicators.csv",
        "narrative": (
            "I am reporting defensive threat-intelligence information concerning the cross-platform "
            "NodeRabbit malware documented by Kaspersky GReAT on September 1, 2026. Kaspersky reports "
            "that attackers posing as recruiters delivered malicious coding assessments containing "
            "bundled Node.js components. The malware supports Windows, Linux and macOS, with later "
            "variants adding enterprise-proxy support, WSL persistence, mutable command-and-control "
            "configuration, a fake local VS Code extension displayed as GitHub Copilot Helper, and "
            "persistence through local Git post-merge and post-checkout hooks. Kaspersky attributes "
            "the campaign to Mirage Kitten; I am identifying that attribution as Kaspersky's "
            "assessment rather than as an independently established conclusion. PollCat, co-disclosed "
            "in the same article, is filed separately (ETW-POL-IC3); RankChallenge-react is a PollCat "
            "lure, not a NodeRabbit IOC."
        ),
        "sources_extra": (
            "## Lineage note\n\n"
            "- `shared/lineage/pollcat-noderabbit-lineage-note.md` — Moderate delivery overlap / "
            "High implant divergence; do not merge authorship with PollCat.\n"
        ),
        "key_caveats": [
            "Mirage Kitten attribution is Kaspersky's assessment — not independently established by ETW.",
            "Git hooks are local persistence unless further evidence shows repository/supply-chain propagation.",
            "Preserve published MD5 archive hashes; SHA-256 enrichment still pending authorized metadata (OPEN).",
            "agent:servers can replace C2 lists — domain IOCs are perishable; prefer host artifacts.",
            "Azure/Cloudflare edge IPs are not actor-owned infrastructure.",
            "RankChallenge-react MD5 (795e053a…) is PollCat — NRB-IND-0011 is CROSS_REF_POLLCAT only; do not treat as NodeRabbit IOC.",
            "Pattern-based NameCheap domains (NRB-IND-0029–0039) and PolySwarm SHA-256s (NRB-IND-0040–0041) are ASSOCIATION_ONLY / RELATED_SAMPLE — not sample-bound NodeRabbit implant proof.",
            "COMMON TECHNIQUE overlap with PollCat (recruiter ZIP / Azure-CF C2) is Moderate; implant divergence is High — see shared/lineage/pollcat-noderabbit-lineage-note.md. Do not merge authorship.",
        ],
        "key_indicators_highlight": [
            "10 Kaspersky-published NodeRabbit archive MD5 values (Front-Technical-Challenge.zip etc.); RankChallenge MD5 lives under POL-IND-0001",
            "Non-Azure domains: visitfinancedentists.com; healthcomfsdpower.com; msmanagementgrp.com; msmanagementgrpmedia.com",
            "Multiple *.azurewebsites.net hosts (see 03_INDICATORS.csv)",
            "NameCheap pattern assets NRB-IND-0029–0039 (ASSOCIATION_ONLY); PolySwarm RELATED_SAMPLE SHA-256 NRB-IND-0040–0041",
            "Host pivots: shepherd-persist Git hooks; fake GitHub Copilot Helper VS Code extension; Linux paths under ~/.config/microsoft-edge-update and ~/.config/intel-dsa",
        ],
        "impact": (
            "Unauthorized access to developer workstations and potentially corporate environments "
            "via proxy-aware C2; espionage risk per Kaspersky campaign framing."
        ),
        "not_claiming": [
            "No independent Mirage Kitten attribution by ETW.",
            "No confirmed supply-chain propagation via Git hooks.",
            "No dollar loss figure.",
            "No claim that current Azure edge IPs are exclusive actor property.",
            "No claim that NodeRabbit and PollCat share implant authors/operators (Moderate delivery overlap only).",
            "No confirmed MD5→SHA-256 map for Kaspersky archive MD5s (including PolySwarm RELATED_SAMPLE rows).",
        ],
    },
    {
        "id": "05-pollcat",
        "family": "PollCat",
        "slug": "pollcat",
        "case_code": "ETW-POL-IC3",
        "platform": "Windows / Linux / macOS",
        "threat_type": "Cross-platform obfuscated JavaScript RAT (coding-challenge delivery)",
        "ic3_crime_types": (
            "Malware; Spear-phishing / social engineering (recruitment lure)"
        ),
        "fbi_relevance": (
            "Co-disclosed with NodeRabbit in Kaspersky Securelist; packages remain separate. "
            "RankChallenge-react lure; distinct C2/persistence from NodeRabbit; stronger documented "
            "protocol overlap with MiniFast/Retrograde than with NodeRabbit."
        ),
        "primary_orgs": "Kaspersky GReAT / Securelist",
        "primary_urls": [
            "https://securelist.com/mirage-kitten-new-backdoors-noderabbit-pollcat/121244/",
        ],
        "pub_date": "2026-09-01 (Securelist)",
        "indicators_path": ROOT
        / "investigations"
        / "pollcat"
        / "evidence"
        / "published-indicators.csv",
        "sources_extra": (
            "## Lineage note\n\n"
            "- `shared/lineage/pollcat-noderabbit-lineage-note.md` — Moderate delivery overlap / "
            "High implant divergence with NodeRabbit; PollCat↔MiniFast protocol alignment is stronger.\n"
            "- Dual-ref primary HTML: same bytes as NodeRabbit `PS-NRB-001` — **do not merge cases**.\n"
        ),
        "narrative": (
            "I am reporting defensive threat-intelligence information concerning the PollCat malware "
            "documented by Kaspersky GReAT on September 1, 2026 in the same Securelist article that "
            "covers NodeRabbit. Kaspersky describes PollCat as a cross-platform obfuscated JavaScript "
            "RAT delivered through the RankChallenge-react coding-challenge archive (MD5 "
            "795e053a990a1569ffdcb57f48f6d085). Kaspersky reports registration C2 hosts including "
            "sahi-finance.com and Azure Web App hostnames, OTP validation via lifespotify.com, and "
            "persistence markers such as NetSync scheduled tasks, requireObject.js under AppData, "
            "com.harsh.requireobject.plist, and ~/.node_packages. Kaspersky states PollCat's structure "
            "is substantially different from NodeRabbit. I am retaining PollCat as a separate case. "
            "Co-disclosure and shared recruiter/coding-challenge delivery are COMMON TECHNIQUE only — "
            "not proof of shared implant authorship. I have not executed malware samples and have not "
            "contacted suspected command-and-control systems."
        ),
        "key_caveats": [
            "Do not equate PollCat operators/authors with NodeRabbit — Moderate delivery overlap / High implant divergence (shared/lineage/pollcat-noderabbit-lineage-note.md).",
            "RankChallenge MD5 is PollCat (POL-IND-0001); any NodeRabbit cross-ref is CROSS_REF_POLLCAT only.",
            "PollCat C2 handshake (HTTP 400 + socketId /gate/*) aligns more with MiniFast/Retrograde than NodeRabbit AES-GCM — do not cite as PollCat≡NodeRabbit code reuse.",
            "Azure Web App / Cloudflare-backed hosts are shared-edge ASSOCIATION_ONLY for ownership.",
            "Mirage Kitten attribution remains Kaspersky's assessment — not an ETW conclusion.",
            "ETW has not independently OBSERVED live campaign infrastructure.",
        ],
        "key_indicators_highlight": [
            "RankChallenge-react MD5 POL-IND-0001: 795e053a990a1569ffdcb57f48f6d085 (not NodeRabbit)",
            "C2 domains: sahi-finance.com; gamebarappinformation.azurewebsites.net; gamebarapp.azurewebsites.net; lifespotify.com",
            "OTP URL path under lifespotify.com (do not probe live)",
            "Persistence: NetSync_* task; requireObject.js; com.harsh.requireobject.plist; ~/.node_packages",
            "Protocol markers: POST /beacon; GET /gate/fetch; POST /gate/hello; POST /api/system-details/result",
            "See 03_INDICATORS.csv (POL-IND-0001–0015)",
        ],
        "impact": (
            "Unauthorized access to developer workstations via coding-challenge social engineering, "
            "per Kaspersky framing."
        ),
        "not_claiming": [
            "No claim that PollCat and NodeRabbit share implant authors/operators.",
            "No dollar loss figure.",
            "No assertion that ETW discovered PollCat.",
            "No fabricated hashes or C2 hosts.",
            "No independent Mirage Kitten attribution by ETW.",
        ],
    },
    {
        "id": "06-synkloader",
        "family": "SynkLoader",
        "slug": "synkloader",
        "case_code": "ETW-SYN-IC3",
        "platform": "Windows (enterprise)",
        "threat_type": "Modular mixed-language loader / credential theft / tunneling",
        "ic3_crime_types": (
            "Malware; Phishing / social engineering (Teams IT-helpdesk lure); Credential theft"
        ),
        "fbi_relevance": (
            "Teams helpdesk phishing with fake lock-screen credential theft and tunneling "
            "into enterprise environments."
        ),
        "primary_orgs": "Expel",
        "primary_urls": [
            "https://expel.com/blog/synkloader-when-you-throw-in-everything-but-the-kitchen-sink/",
        ],
        "pub_date": "2026-08-20 (Expel / Marcus Hutchins)",
        "observed_infra": (
            "OBSERVED_PASSIVE DNS A only for four Expel C2 domains (SYN-IND-0026–0029); "
            "no live C2 contact. Azure MSI edge IP is ASSOCIATION_ONLY."
        ),
        "indicators_path": ROOT
        / "investigations"
        / "synkloader"
        / "evidence"
        / "published-indicators.csv",
        "narrative": (
            "I am reporting defensive threat-intelligence information concerning SynkLoader as "
            "publicly documented by Expel on August 20, 2026. Expel describes a modular mixed-language "
            "loader delivered through Microsoft Teams phishing posing as IT helpdesk (external "
            "*.onmicrosoft.com tenant, display name IT Service Desk), with initial MSI hosted on "
            "Azure Blob Storage (filereserve.blob.core.windows.net/.../331.msi, product name "
            "PowershellCleaner). Expel reports nested PowerShell decryption into an in-memory Python "
            "loader (ss.py), fake Visual C++ DLLs (msvcp150.dll / msvcp160.dll), a fake Windows 11 "
            "lock-screen credential-theft module (PhishLocker), and additional modules including "
            "TrafficRedirector and StreamMaster VNC. Expel published loader C2 domains "
            "neversoftmain.net, rootfarmapp.net, and tripinupdate.net; TrafficRedirector C2 "
            "dondermicapp.net; StreamMaster C2 aroclenetapp.net; and modified ChaCha20 sigma "
            "constants mlswgtppayebtezk / lwifnrfiosmfrubf. I have retained the public research and "
            "indicator records. Passive DNS A mappings for selected published domains are labeled "
            "OBSERVED_PASSIVE and are not live command-and-control contact. I have not executed "
            "malware samples and have not contacted suspected command-and-control systems."
        ),
        "key_caveats": [
            "Domain/hash/URL rows are PRIMARY-SOURCE (Expel); IPv4 rows SYN-IND-0026–0029 are "
            "OBSERVED_PASSIVE DNS A mappings — not live C2 contact.",
            "CDN demotion N/A for these non-CDN C2 A records; author identity remains NOT_ESTABLISHED.",
            "Shared ASN AS399629 across multiple apexes is INFRASTRUCTURE_OVERLAP candidate only — not operator identity.",
            "Azure Blob MSI host edge IP is ASSOCIATION_ONLY (not actor-owned).",
            "Secondary ransomware-follow-on / IAB framing is Expel low–medium confidence or secondary press — not established by ETW.",
            "Resolving a published domain != proof C2 is currently active.",
        ],
        "key_indicators_highlight": [
            "Delivery URL (Expel): https://filereserve.blob.core.windows.net/vgnghuyk/331/331.msi",
            "SHA-256 (Expel): 331.msi; cleaner.ps1; archive6.zip; ss.py; msvcp150/160.dll; module loaders — see 03_INDICATORS.csv",
            "C2 domains (Expel PRIMARY): neversoftmain.net; rootfarmapp.net; tripinupdate.net; dondermicapp.net; aroclenetapp.net",
            "C2 IPv4 (OBSERVED_PASSIVE A): 149.248.76.220; 162.33.177.8; 216.245.184.14; 64.94.85.67",
            "ChaCha sigma constants (Expel): mlswgtppayebtezk; lwifnrfiosmfrubf",
            "PDB path (Expel): C:\\Users\\genry\\source\\repos\\pwshnewdll\\...\\pwshnewdll.pdb",
            "See 03_INDICATORS.csv (SYN-IND-0001–0029)",
        ],
        "impact": (
            "Credential theft and potential tunnel-enabled access to internal/external systems "
            "via the infected host, per Expel framing."
        ),
        "not_claiming": [
            "No dollar loss figure.",
            "No assertion that ETW discovered SynkLoader.",
            "No fabricated hashes or C2 hosts.",
            "No confirmed ransomware follow-on by ETW.",
            "No author identity claim (NOT_ESTABLISHED).",
        ],
    },
    {
        "id": "07-showboat",
        "family": "Showboat",
        "slug": "showboat",
        "case_code": "ETW-SHO-IC3",
        "platform": "Linux (telecom / ISP environments)",
        "threat_type": "Linux modular post-exploitation framework",
        "ic3_crime_types": "Malware; Unauthorized network intrusion (post-exploitation)",
        "fbi_relevance": (
            "Telecom-oriented Linux post-exploitation; historical activity may predate "
            "2026 public disclosure."
        ),
        "primary_orgs": "Lumen Black Lotus Labs",
        "primary_urls": [
            "https://www.lumen.com/blog/en-us/introducing-showboat-a-new-malware-family-taunts-defenses-and-targets-international-telecom-firms",
            "https://raw.githubusercontent.com/blacklotuslabs/IOCs/main/Showboat_IOCs.txt",
        ],
        "pub_date": "2026 (possible activity ≥2022)",
        "indicators_path": ROOT
        / "investigations"
        / "showboat"
        / "evidence"
        / "published-indicators.csv",
        "narrative": (
            "I am reporting defensive threat-intelligence information concerning Showboat as "
            "publicly documented by Lumen Black Lotus Labs (May 2026 disclosure). Lumen describes a "
            "modular Linux post-exploitation framework used against telecommunications organizations. "
            "Published artifacts support historical activity: a Pastebin hide-code drop first posted "
            "in January 2022 and Black Lotus Labs IOC hosts first seen as early as 2023-04-04. "
            "Historical activity versus disclosure date remains an intelligence gap. Lumen publishes "
            "C2 and impersonation infrastructure including telecom.webredirect.org resolving to "
            "139.84.227.139, related hosts, sample SHA-256 values (including Linux "
            "d6a4fad5448838dbc8cc6b33f1dbfbdc7a2fad36de58ff6a66dce96f729f7011), and a hardcoded XOR "
            "config key. I have retained the public research URL and the published Showboat_IOCs.txt "
            "appendix. I have not executed malware samples and have not contacted suspected "
            "command-and-control systems."
        ),
        "key_caveats": [
            "Historical activity (Pastebin Jan 2022; BLL IPs from 2023-04) vs May 2026 disclosure dating is an intelligence gap — do not collapse into first-seen 2026.",
            "IPv4/domain/hash rows are PRIMARY-SOURCE from Lumen article and BLL Showboat_IOCs.txt — not ETW live contact.",
            "116.169.244.208 is ASSOCIATION_ONLY (possible upstream/dev) — not confirmed actor-owned C2.",
            "CDN demotion N/A for these BLL/Lumen-listed hosts; author identity remains NOT_ESTABLISHED (vendor cites PRC-aligned clusters — ETW does not independently establish).",
            "Do not invent additional telecom victim names or backdate beyond published ranges.",
        ],
        "key_indicators_highlight": [
            "Primary C2: telecom.webredirect.org → 139.84.227.139; second C2 194.135.25.132",
            "Impersonation: singtelcom.site @ 23.27.201.160; kaztelecom.shop @ 101.36.105.222",
            "Linux sample SHA-256: d6a4fad5448838dbc8cc6b33f1dbfbdc7a2fad36de58ff6a66dce96f729f7011",
            "Historical hosting: 103.10.145.129 (first_seen 2023-04-04); Pastebin hide-code Jan 2022",
            "BLL C2 table IPv4 set plus secondary cluster 192.9.141.111 / 64.176.43.209",
            "See 03_INDICATORS.csv (SHO-IND-0001–0026)",
        ],
        "impact": (
            "Persistent unauthorized access in Linux telecom/ISP environments, per Lumen framing."
        ),
        "not_claiming": [
            "No dollar loss figure.",
            "No assertion that ETW discovered Showboat.",
            "No fabricated hashes or C2 hosts.",
            "No independent actor attribution beyond vendor language.",
            "No claim that Pastebin Jan 2022 alone proves continuous Showboat operations through 2026.",
        ],
        "sources_extra": (
            "## Local archive\n\n"
            "- `evidence/primary-sources/showboat/Showboat_IOCs_2026-09-19T190009Z.txt`\n"
            "- `evidence/primary-sources/showboat/lumen-showboat.html` (PS-SHO-001)\n"
        ),
    },
]

ADDENDUM = """
---
ADDITIONAL CONTEXT FOR THE COMPLAINT (OPTIONAL SHORT ADDENDUM)
Research cutoff: 2026-09-19. This report is based on publicly published vendor/research reporting retained for defensive and law-enforcement correlation. I have not executed malware samples and have not authenticated to or interacted with suspected command-and-control systems. Indicators listed in the accompanying CSV are PRIMARY-SOURCE (published by the cited researchers) and are not independently re-validated live observations unless separately marked OBSERVED.
""".strip()


def write_package(fam: dict) -> None:
    d = PACKAGES / fam["id"]
    d.mkdir(parents=True, exist_ok=True)

    cover = f"""# {fam['family']} — Law Enforcement Package Cover Sheet

| Field | Value |
|-------|-------|
| **Package ID** | `{fam['case_code']}` |
| **Family** | {fam['family']} only (case-isolated) |
| **Platform** | {fam['platform']} |
| **Threat type** | {fam['threat_type']} |
| **Research cutoff** | 2026-09-19 |
| **Corpus retrieval** | 2026-09-19T18:07:48Z |
| **Package status** | DRAFT — human review required before any filing |
| **ETW independently observed infrastructure** | {fam.get('observed_infra', '**None**')} |
| **Suggested IC3 crime-type language** | {fam['ic3_crime_types']} |
| **FBI relevance (defensive TI)** | {fam['fbi_relevance']} |
| **Primary research orgs** | {fam['primary_orgs']} |
| **Primary publication window** | {fam['pub_date']} |

## Package contents (file in this order)

| # | File | Purpose |
|---|------|---------|
| 00 | `00_COVER_SHEET.md` | This sheet |
| 01 | `01_NARRATIVE_PASTE.txt` | Plain-text paste into IC3 complaint description |
| 02 | `02_FBI_SUMMARY.md` | Short FBI / field-office oriented summary |
| 03 | `03_INDICATORS.csv` | Source-attributed indicators (PRIMARY-SOURCE; not OBSERVED) |
| 04 | `04_SOURCES.md` | Exact public URLs and roles |
| 05 | `05_CAVEATS_AND_LIMITS.md` | What this package does **not** claim |
| 06 | `06_EVIDENCE_RETAINED.md` | What the reporter should retain locally |

## Filing rule

Submit **this package alone**. Do **not** combine with other Emerging Threat Watch family filings unless a human reviewer documents linkage evidence and decides a joint filing is appropriate.

## Integrity gate (must all pass)

- [ ] Narrative uses "researchers reported" / "I retained" language — not "I discovered" unless true
- [ ] No unsupported victimization or dollar-loss claims
- [ ] No fabricated hashes, domains, or C2 hosts
- [ ] Attribution provenance preserved (vendor assessment vs ETW conclusion)
- [ ] Current vs historical infrastructure distinguished
- [ ] Human reviewer name/date recorded before submit
"""
    (d / "00_COVER_SHEET.md").write_text(cover, encoding="utf-8")

    (d / "01_NARRATIVE_PASTE.txt").write_text(
        fam["narrative"].strip() + "\n\n" + ADDENDUM + "\n", encoding="utf-8"
    )

    bullets = "\n".join(f"- {x}" for x in fam["key_indicators_highlight"])
    caveats = "\n".join(f"- {x}" for x in fam["key_caveats"])
    fbi = f"""# {fam['family']} — FBI / Field-Office Summary

**Package:** `{fam['case_code']}` · **Status:** DRAFT · **Cutoff:** 2026-09-19

## One-paragraph summary

{fam['narrative'].strip()}

## Why this may matter to FBI cyber / IC3 correlation

{fam['fbi_relevance']}

## Highest-value indicators (primary-source; not ETW-observed)

{bullets}

Full table: `03_INDICATORS.csv`

## Critical analytical caveats

{caveats}

## Suggested handling

1. Treat as **defensive threat-intelligence referral**, not a completed criminal case file.
2. Correlate MeshAgent / domain / hash / URI-path indicators against existing FBI/IC3 holdings.
3. Request sample acquisition through normal vendor/legal channels if needed — this package does not contain malware binaries.
4. Keep this family **separate** from other Emerging Threat Watch packages unless linkage evidence appears.

## Contact block (reporter fills before filing)

| Field | Value |
|-------|-------|
| Reporter name | _[TO BE FILLED]_ |
| Organization (if any) | _[TO BE FILLED]_ |
| Email / phone | _[TO BE FILLED]_ |
| Preferred contact method | _[TO BE FILLED]_ |
| Related IC3 complaint number(s) | _[IF ANY]_ |
| Related FBI tip / case number(s) | _[IF ANY]_ |
"""
    (d / "02_FBI_SUMMARY.md").write_text(fbi, encoding="utf-8")

    shutil.copy2(fam["indicators_path"], d / "03_INDICATORS.csv")

    urls = "\n".join(f"- {u}" for u in fam["primary_urls"])
    sources_extra = fam.get("sources_extra", "")
    if sources_extra and not sources_extra.endswith("\n"):
        sources_extra += "\n"
    (d / "04_SOURCES.md").write_text(
        f"""# {fam['family']} — Primary Sources

**Package:** `{fam['case_code']}`

## Organizations

{fam['primary_orgs']}

## Copy-pasteable URLs

{urls}

{sources_extra}## Provenance rule

These URLs are **PRIMARY-SOURCE** publications. Retrieving or retaining them does **not** make infrastructure `OBSERVED` by the Emerging Threat Watch investigation.
""",
        encoding="utf-8",
    )

    nots = "\n".join(f"- {x}" for x in fam["not_claiming"])
    cavs = "\n".join(f"- {x}" for x in fam["key_caveats"])
    (d / "05_CAVEATS_AND_LIMITS.md").write_text(
        f"""# {fam['family']} — Caveats and Limits

**Package:** `{fam['case_code']}`

## Analytical caveats

{cavs}

## This package does **not** claim

{nots}

## Potential impact (general; not a loss claim)

{fam['impact']}

## Provenance vocabulary (for reviewers)

| Label | Meaning in this package |
|-------|-------------------------|
| PRIMARY-SOURCE | Published by the cited vendor/researcher |
| OBSERVED_PASSIVE | Passive fact retrieved by ETW (CT/DNS/urlscan/RDAP) — not ownership |
| OBSERVED | Independently observed campaign ownership (not claimed in baseline) |
| INFERRED | Analytical conclusion — labeled as such |
| UNVERIFIED | Exists as lead but not adequately substantiated |

## Safety statement

No malware was executed and no suspected command-and-control system was contacted during preparation of this package.
""",
        encoding="utf-8",
    )

    slug = fam["slug"]
    lineage_row = ""
    if fam["slug"] in ("noderabbit", "pollcat"):
        lineage_row = (
            "| Lineage note | `shared/lineage/pollcat-noderabbit-lineage-note.md` |\n"
        )
    (d / "06_EVIDENCE_RETAINED.md").write_text(
        f"""# {fam['family']} — Evidence Retained (Reporter Checklist)

**Package:** `{fam['case_code']}`

Retain locally (do not upload malware binaries to IC3 web forms):

- [ ] Saved copies / screenshots of primary research pages listed in `04_SOURCES.md` (HTML + timestamp)
- [ ] This package folder (all seven files)
- [ ] Full ETW investigation folder if available: `investigations/{slug}/`
- [ ] Any **independent** OBSERVED validation results (CT/pDNS/hash enrichment) — label clearly as OBSERVED with date/method
- [ ] Reporter contact information and any related complaint/tip numbers

## Do not include in public IC3 text fields unless asked

- Full malware binaries or packed archives
- Victim PII beyond what IC3 explicitly requests
- Credentials, session tokens, or private keys obtained from any environment
- Active C2 interaction logs (ETW policy forbids C2 contact)

## Repository cross-reference (Emerging Threat Watch)

| Artifact | Path |
|----------|------|
| Indicators | `investigations/{slug}/evidence/published-indicators.csv` |
| Claims | `investigations/{slug}/claims/claims-ledger.csv` |
| Gaps | `investigations/{slug}/gaps/priority-gaps.csv` |
{lineage_row}| IC3 draft (repo) | `reports/{slug}/{fam['family'].upper()}_IC3_BRIEF.md` |
| This LE package | `reports/law-enforcement/packages/{fam['id']}/` |
""",
        encoding="utf-8",
    )
    print("wrote", fam["id"])


def main() -> None:
    PACKAGES.mkdir(parents=True, exist_ok=True)
    for fam in FAMILIES:
        write_package(fam)
    print("OK", len(FAMILIES), "packages ->", PACKAGES)


if __name__ == "__main__":
    main()
